version: "3"
services:
  java:
    # 指定容器名称
    container_name: sms-api
    image: openjdk:8
    restart: always
    volumes:
      # 本地jar包路径
      - ./target/sales-sys-admin-api-1.0-SNAPSHOT.jar:/ROOT.jar
      # 挂载日志 -v A:B ,A指宿主机位置，B指容器位置
      - ./logs:/logs
    # 访问端口
    ports:
      - "8090:8090"
    environment:
      # 指定时区
      - TZ="Asia/Shanghai"
    #启动容器后执行的命令
    entrypoint: java -server -Xms256m -Xmx256m -jar -Dserver.port=8090 -Dspring.profiles.active=test ROOT.jar

networks:
  default:
    external:
      name: devnet