spring:
  profiles:
    active: dev
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB

  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.dc.project.**.entity
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 0
      # 删除后
      logic-delete-value: 1
      # 指定删除字段
      logic-delete-field: delFlag

logging:
  level:
    com.dc: debug
    org.springfromework.web: info
    com.ulisesbocchio.jasyptspringboot: warn


sms:
  captcha-cache: false
  timeout: 24
  # 防止XSS攻击
  xss:
    # 过滤开关
    enabled: true
    # 排除链接（多个用逗号分隔）
    excludes: /monitor/*
    # 匹配链接
    urlPatterns: /system/*,/basis/*,/fiance/*,/sales/*
  swagger:
    enable: true
    title: Swagger3开发文档
    description: 更多请咨询服务开发者
    name: zhuangcy
    url: https://zhuangcy.top
    email: 1909017815@qq.com
    version: 1.0.0
    protocols: http,https
