server:
  port: 8090
  servlet:
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
  ssl:
    key-store: classpath:service.jks
    key-store-password: ENC(ZI+pV7kgbpv8fvbjDkOJBi+MSHLsuw+a)
    key-store-type: JKS


spring:
  application:
    name: sales-sys-admin
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.120.197:3306/smsdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: ENC(WimeGc6kI7YEgR15oV9FCw==)
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 10000
      connection-test-query: SELECT 1

sms:
  ftp:
    host: 172.16.120.197
    port: 21
    username: zhuangcy
    password: zhuangcy
    path: /home/zhuangcy/ftp
    urlPrefix: http://172.16.120.197:80